### ISSUE TITLE
Handling dates in form YYYY-WW

### ISSUE THREAD

**Issue by Analect** [bowerth/sdmxBrowser#2]
@bowerth 
You got the new site up and running quickly!
I notice in playing around with this time-series: ILM.W.U2.C.A010.Z5.Z0Z
... that the YYYY-WW date format isn't handled in your R script.
Maybe the ISOweek library can help there.
http://www.inside-r.org/packages/cran/ISOweek/docs/ISOweek2date

**Comment by bowerth** [comment]
this might be an issue of RJSDMX - the time series frequency can't be recognized with the `frequency()` function:

``` r
data <- RJSDMX::getSDMX(provider = "ECB",
                        id = "ILM.W.U2.C.A010.Z5.Z0Z",
                        start = "2000",
                        end = "2012"
                        )
frequency(data[[1]])
```

returns `NULL` whereas 

``` r
data2 <- RJSDMX::getSDMX(provider = "ABS",
                         id = "LF.0.1.1.1519.10.M",
                         start = "2000",
                         end = "2012"
                         )
frequency(data2[[1]])
```

returns `12`

you may want to raise this issue in https://github.com/amattioc/SDMX/ directly?

**Comment by Analect** [comment]
@bowerth 
Perhaps your periodicity test could use string matching instead, by leveraging attr() against the 'FREQ' metadata.

such as this for weekly:

```
> attr(getSDMX('ECB', 'ILM.W.U2.C.A010.Z5.Z0Z', '2014-01-01','2015-01-01')[[1]],'FREQ')
Apr 24, 2015 5:34:19 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: http://sdw-wsrest.ecb.europa.eu/service/data/ECB,ILM,1.0/W.U2.C.A010.Z5.Z0Z?startPeriod=2014-01-01&endPeriod=2015-01-01
[1] "W"
```

.. and this for monthly:

```
> attr(getSDMX('ECB', 'ILM.M.U2.C.LT01.Z5.EUR', '2014-01-01','2015-01-01')[[1]],'FREQ')
Apr 24, 2015 5:34:39 PM it.bancaditalia.oss.sdmx.client.RestSdmxClient runQuery
INFO: Contacting web service with query: http://sdw-wsrest.ecb.europa.eu/service/data/ECB,ILM,1.0/M.U2.C.LT01.Z5.EUR?startPeriod=2014-01-01&endPeriod=2015-01-01
[1] "M"
```

**Comment by bowerth** [comment]
Thanks, that seems to work because the `attr` function only scans first n characters of `attr(x, which)` parameter, i.e. `which = "FREQ"` matches "FREQUENCY"

Added support for `W` frequency following your suggestion of using ISOweek:

``` r
if (queryDataFreq=="W") {
  data.plots$time <- ISOweek2date(paste0(data.plots$time, "-1"))
}
```

Suppressed time series plot for SDMX flows that do not return a time series, i.e. where `getSDMX` returns `Frequency is NULL. Irregular timeseries defined`

```
data3 <- RJSDMX::getSDMX(provider = "ABS",
                         id = "ABS_SEIFA_SA2.0+1+101+10101+101011001.IEO+IER+IRSAD+IRSD.MAXS+MINS+RWA+RWAD",
                         start = "2000",
                         end = "2012")
```

**Comment by Analect** [comment]
Great. Thanks. Will close this out.
