### ISSUE TITLE
Missing file: global.R

### ISSUE THREAD

**Issue by tonyfujs** [bowerth/sdmxBrowser#5]
Hi,

I was trying to run your app locally, but ran into an error:
` cannot open file 'global.R': No such file or directory`

The file seems to be missing from the Github repo.

Thanks!

**Comment by bowerth** [comment]
Hi tonyfujs,
thank you for mentioning - please check if it works for you now.
you can also test a browser developed in Scala: https://github.com/bowerth/sdmxPlay
best,
Bo

**Comment by tonyfujs** [comment]
Thanks @bowerth 
Works fine now, and thanks for the link to the Scala version.
Best,
Tony
